source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "minima", "~> 2.5"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
end

# Optional for local serve (doesn't affect CI)
gem "webrick", "~> 1.8"
