baseURL = "/hugo/"
title = "Hugo Example"
languageCode = "en-us"

[params]
description = "Short site description"
tagline = "Just another Hugo site"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 2

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


# --- Blog basics ---
paginate = 10
summaryLength = 140

[taxonomies]
tag = "tags"
category = "categories"

[permalinks]
posts = "/posts/:slug/"

[outputs]
home = ["HTML","RSS"]
section = ["HTML","RSS"]
