baseURL = "/hugo/"
title = "Hugo Example"
languageCode = "en-us"

[params]
description = "Short site description"
tagline = "Just another Hugo site"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 2
