  set -euo pipefail
    IID=$(aws ec2 describe-instances --filters \
    "Name=tag:Repo,Values=${REPO_TAG}" \
    "Name=tag:Name,Values=ssg-examples" \
    "Name=instance-state-name,Values=running" \
    --query "Reservations[].Instances[].InstanceId" --output text | head -n1)
    [ -n "$IID" ] && [ "$IID" != "None" ] || { echo "No running instance with Repo=${REPO_TAG} AND Name=ssg-examples"; exit 1; }
    HOST=$(aws ec2 describe-instances --instance-ids "$IID" \
    --query "Reservations[].Instances[].PublicDnsName" --output text)
    SGS=$(aws ec2 describe-instances --instance-ids "$IID" \
    --query "Reservations[].Instances[].SecurityGroups[].GroupId" --output text)
    echo "instance_id=$IID" >> "$GITHUB_OUTPUT"
    echo "host=$HOST" >> "$GITHUB_OUTPUT"
    echo "sg_ids=$SGS" >> "$GITHUB_OUTPUT"
    echo "### Deploy target" >> $GITHUB_STEP_SUMMARY
    echo "$HOST" >> $GITHUB_STEP_SUMMARY
